include: 
  - package:lints/recommended.yaml
  # https://github.com/VeryGoodOpenSource/very_good_analysis/blob/main/lib/analysis_options.9.0.0.yaml
  - package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    discarded_futures: ignore
    inference_failure_on_instance_creation: ignore
    invalid_annotation_target: ignore
    lines_longer_than_80_chars: ignore
    one_member_abstracts: ignore
    public_member_api_docs: ignore
    sort_constructors_first: ignore
    specify_nonobvious_property_types: ignore
    strict_raw_type: ignore

    
formatter:
  trailing_commas: preserve
  page_width: 100
